### ISSUE TITLE
Read access is allowed from inside read-action

### ISSUE THREAD

**Issue by scosenza** [wrike/sprinter-idea-plugin#3]
After clicking "Run in launched VM" for a Gradle based project I get the following error. However, the test is able to run and passes.

Sprinter 1.3.2
IntelliJ IDEA 2023.3.4 (Ultimate Edition)

```
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action (see Application.runReadAction()); see https://jb.gg/ij-platform-threading for details
Current thread: Thread[ApplicationImpl pooled thread 5,4,main] 423317760 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 2144334509
	at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:149)
	at com.intellij.util.concurrency.ThreadingAssertions.softAssertReadAccess(ThreadingAssertions.java:107)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1012)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.ensureIsUpToDate(WorkspaceFileIndexDataImpl.kt:134)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.getFileInfo(WorkspaceFileIndexDataImpl.kt:75)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.getFileInfo(WorkspaceFileIndexImpl.kt:247)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getModuleSourceOrLibraryClassesRoot(ProjectFileIndexImpl.java:210)
	at com.intellij.openapi.module.impl.scopes.ModuleWithDependenciesScope.contains(ModuleWithDependenciesScope.java:147)
	at com.intellij.psi.impl.file.PsiPackageImpl.lambda$getAllDirectories$1(PsiPackageImpl.java:67)
	at com.intellij.util.containers.ContainerUtil.findAll(ContainerUtil.java:1030)
	at com.intellij.util.containers.ContainerUtil.filter(ContainerUtil.java:1005)
	at com.intellij.psi.impl.file.PsiPackageImpl.getAllDirectories(PsiPackageImpl.java:67)
	at com.intellij.psi.impl.file.PsiPackageBase.getDirectories(PsiPackageBase.java:63)
	at org.jetbrains.kotlin.idea.debugger.coroutine.CoroutineAgentConnector.getJarVirtualFiles(CoroutineAgentConnector.kt:71)
	at org.jetbrains.kotlin.idea.debugger.coroutine.CoroutineAgentConnector.findKotlinxCoroutinesCoreJar(CoroutineAgentConnector.kt:43)
	at org.jetbrains.kotlin.idea.debugger.coroutine.CoroutineAgentConnector.attachCoroutineAgent(CoroutineAgentConnector.kt:33)
	at org.jetbrains.kotlin.idea.debugger.coroutine.DebuggerConnection.<init>(DebuggerConnection.kt:51)
	at org.jetbrains.kotlin.idea.debugger.coroutine.DebuggerConnection.<init>(DebuggerConnection.kt:31)
	at org.jetbrains.kotlin.idea.debugger.coroutine.CoroutineDebugConfigurationExtension.updateJavaParameters(CoroutineDebugConfigurationExtension.kt:24)
	at com.intellij.execution.RunConfigurationExtension.updateJavaParameters(RunConfigurationExtension.java:27)
	at com.intellij.execution.JavaRunConfigurationExtensionManager.updateJavaParameters(JavaRunConfigurationExtensionManager.kt:42)
	at com.wrike.sprinter.frameworks.AbstractSharedJvmRunnableState.createJavaParameters(AbstractSharedJvmRunnableState.kt:80)
	at com.wrike.sprinter.frameworks.junit.SharedJvmJUnitRunnableState.createJavaParameters(SharedJvmJUnitRunnableState.kt:27)
	at com.intellij.execution.configurations.JavaCommandLineState.getJavaParameters(JavaCommandLineState.java:41)
	at com.intellij.debugger.impl.GenericDebuggerRunner.lambda$doExecute$2(GenericDebuggerRunner.java:82)
	at com.intellij.execution.runners.JavaProgramPatcher.lambda$patchJavaCommandLineParamsUnderProgress$2(JavaProgramPatcher.java:41)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:287)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:132)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$8(CoreProgressManager.java:518)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:84)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:248)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:248)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:498)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:86)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:81)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:464)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by scosenza** [comment]
<img width="968" alt="Screenshot 2024-03-01 at 8 25 04 AM" src="https://github.com/wrike/sprinter-idea-plugin/assets/1959317/886bb343-51a2-43f0-9d36-15f72d2dd76f">

**Comment by Mugenor** [comment]
Hi!

Thanks for reporting the issue. 
I wasn't able to reproduce the issue, but I think I found the problem.
I've uploaded update, it should be available soon. Let me know, if it fixes the problem
